//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 03:36:25 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://resenje", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package paket;
