package com.xml.portal.eposta.soap;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T12:04:53.382+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "EpostaService", 
                  wsdlLocation = "classpath:wsdl/zahtev.wsdl",
                  targetNamespace = "http://posta") 
public class EpostaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://posta", "EpostaService");
    public final static QName EpostaServiceSoapBinding = new QName("http://posta", "EpostaServiceSoapBinding");
    static {
        URL url = EpostaService.class.getClassLoader().getResource("wsdl/zahtev.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(EpostaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/zahtev.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public EpostaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EpostaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EpostaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EpostaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EpostaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EpostaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns EpostaServicePortType
     */
    @WebEndpoint(name = "EpostaServiceSoapBinding")
    public EpostaServicePortType getEpostaServiceSoapBinding() {
        return super.getPort(EpostaServiceSoapBinding, EpostaServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EpostaServicePortType
     */
    @WebEndpoint(name = "EpostaServiceSoapBinding")
    public EpostaServicePortType getEpostaServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(EpostaServiceSoapBinding, EpostaServicePortType.class, features);
    }

}
