//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.08 at 11:02:37 PM CET 
//


package com.xml.portal.poverenik.data.dao.obavestenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Zakonska_osnova" type="{http://obavestenje}TZakon"/>
 *         &lt;element name="Datum_potrazivanja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Opis_trazene_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Podaci_o_uvidu" type="{http://obavestenje}TVremeMesto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zakonskaOsnova",
    "datumPotrazivanja",
    "opisTrazeneInformacije",
    "podaciOUvidu"
})
@XmlRootElement(name = "Uvid_u_dokument", namespace = "http://obavestenje")
public class UvidUDokument {

    @XmlElement(name = "Zakonska_osnova", namespace = "http://obavestenje", required = true)
    protected TZakon zakonskaOsnova;
    @XmlElement(name = "Datum_potrazivanja", namespace = "http://obavestenje", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPotrazivanja;
    @XmlElement(name = "Opis_trazene_informacije", namespace = "http://obavestenje", required = true)
    protected String opisTrazeneInformacije;
    @XmlElement(name = "Podaci_o_uvidu", namespace = "http://obavestenje", required = true)
    protected TVremeMesto podaciOUvidu;

    /**
     * Gets the value of the zakonskaOsnova property.
     * 
     * @return
     *     possible object is
     *     {@link TZakon }
     *     
     */
    public TZakon getZakonskaOsnova() {
        return zakonskaOsnova;
    }

    /**
     * Sets the value of the zakonskaOsnova property.
     * 
     * @param value
     *     allowed object is
     *     {@link TZakon }
     *     
     */
    public void setZakonskaOsnova(TZakon value) {
        this.zakonskaOsnova = value;
    }

    /**
     * Gets the value of the datumPotrazivanja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPotrazivanja() {
        return datumPotrazivanja;
    }

    /**
     * Sets the value of the datumPotrazivanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPotrazivanja(XMLGregorianCalendar value) {
        this.datumPotrazivanja = value;
    }

    /**
     * Gets the value of the opisTrazeneInformacije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpisTrazeneInformacije() {
        return opisTrazeneInformacije;
    }

    /**
     * Sets the value of the opisTrazeneInformacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpisTrazeneInformacije(String value) {
        this.opisTrazeneInformacije = value;
    }

    /**
     * Gets the value of the podaciOUvidu property.
     * 
     * @return
     *     possible object is
     *     {@link TVremeMesto }
     *     
     */
    public TVremeMesto getPodaciOUvidu() {
        return podaciOUvidu;
    }

    /**
     * Sets the value of the podaciOUvidu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVremeMesto }
     *     
     */
    public void setPodaciOUvidu(TVremeMesto value) {
        this.podaciOUvidu = value;
    }

}
