//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.08 at 11:32:30 PM CET 
//


package com.xml.portal.poverenik.data.dao.zalba_odbijanje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml.portal.poverenik.data.dao.zalba_odbijanje package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml.portal.poverenik.data.dao.zalba_odbijanje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalbaOdbijanje }
     * 
     */
    public ZalbaOdbijanje createZalbaOdbijenZahtev() {
        return new ZalbaOdbijanje();
    }

    /**
     * Create an instance of {@link ZalbaOdbijanje.PodaciOOdluci }
     * 
     */
    public ZalbaOdbijanje.PodaciOOdluci createZalbaOdbijenZahtevPodaciOOdluci() {
        return new ZalbaOdbijanje.PodaciOOdluci();
    }

    /**
     * Create an instance of {@link TTelo }
     * 
     */
    public TTelo createTTelo() {
        return new TTelo();
    }

}
