
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xml.portal.organvlasti.service.soap.resenje;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.w3c.dom.Document;

import com.xml.portal.organvlasti.business.ResenjeBusiness;

//import resenje.Resenje;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-06T08:44:31.386+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ResenjeService",
                      portName = "ResenjeServiceSoapBinding",
                      targetNamespace = "http://resenje",
                      wsdlLocation = "src/main/resources/data/wsdl/resenje.wsdl",
                      endpointInterface = "com.xml.portal.organvlasti.service.soap.resenje.ResenjeServicePortType")
@Service             
public class ResenjeServiceSoapBindingImpl implements ResenjeServicePortType {

    private static final Logger LOG = Logger.getLogger(ResenjeServiceSoapBindingImpl.class.getName());
    
    @Autowired
    private ResenjeBusiness resenjeBusiness;
    /* (non-Javadoc)
     * @see resenje.ResenjeServicePortType#receiveResenje(resenje.Resenje resenje)*
     */
    public void receiveResenje(Document resenje) { 
        LOG.info("Executing operation receiveResenje");
        System.out.println(resenje);
        try {
//        	String documentId = resenjeBusiness.saveToDB(resenje);
//        	System.out.println(documentId);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
