
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xml.portal.organvlasti.service.soap.resenje;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.w3c.dom.Document;

import com.xml.portal.organvlasti.business.ResenjeBusiness;
import com.xml.portal.organvlasti.data.dao.odgovor.Odgovor;
import com.xml.portal.organvlasti.data.dao.soap.resenje.Resenje;



/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-06T08:44:31.386+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ResenjeService",
                      portName = "ResenjeServiceSoapBinding",
                      targetNamespace = "http://resenje",
                      wsdlLocation = "src/main/resources/data/wsdl/resenje.wsdl",
                      endpointInterface = "com.xml.portal.organvlasti.service.soap.resenje.ResenjeServicePortType")
@Service             
public class ResenjeServiceSoapBindingImpl implements ResenjeServicePortType {

    private static final Logger LOG = Logger.getLogger(ResenjeServiceSoapBindingImpl.class.getName());
    
    @Autowired
    private ResenjeBusiness resenjeBusiness;
    /* (non-Javadoc)
     * @see resenje.ResenjeServicePortType#receiveResenje(resenje.Resenje resenje)*
     */
    public void receiveResenje(Resenje resenje) { 
        LOG.info("Executing operation receiveResenje");
        System.out.println(resenje);
        try {
        	JAXBContext jc = JAXBContext.newInstance(Resenje.class);
        	DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
    		DocumentBuilder db = dbf.newDocumentBuilder();
    		Document document = db.newDocument();


    		// Marshal the Object to a Document
    		Marshaller marshaller = jc.createMarshaller();
    		marshaller.marshal(resenje, document);
//    		System.out.println(document);
        	String documentId = resenjeBusiness.saveToDB(document);
        	System.out.println(documentId);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
