//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 09:57:22 PM CET 
//


package zalba_odbijen;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zalba_odbijen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zalba_odbijen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalbaOdbijenZahtev }
     * 
     */
    public ZalbaOdbijenZahtev createZalbaOdbijenZahtev() {
        return new ZalbaOdbijenZahtev();
    }

    /**
     * Create an instance of {@link TPrimalac }
     * 
     */
    public TPrimalac createTPrimalac() {
        return new TPrimalac();
    }

    /**
     * Create an instance of {@link TZalilac }
     * 
     */
    public TZalilac createTZalilac() {
        return new TZalilac();
    }

    /**
     * Create an instance of {@link ZalbaOdbijenZahtev.PodaciOOdluci }
     * 
     */
    public ZalbaOdbijenZahtev.PodaciOOdluci createZalbaOdbijenZahtevPodaciOOdluci() {
        return new ZalbaOdbijenZahtev.PodaciOOdluci();
    }

    /**
     * Create an instance of {@link TTelo }
     * 
     */
    public TTelo createTTelo() {
        return new TTelo();
    }

    /**
     * Create an instance of {@link TPodnosilac }
     * 
     */
    public TPodnosilac createTPodnosilac() {
        return new TPodnosilac();
    }

}
