//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 09:57:22 PM CET 
//


package zalba_odbijen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TZalilac complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TZalilac">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="ime_i_prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="naziv_zalioca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *         &lt;element name="adresa_zalioca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TZalilac", propOrder = {
    "imeIPrezime",
    "nazivZalioca",
    "adresaZalioca"
})
public class TZalilac {

    @XmlElement(name = "ime_i_prezime")
    protected String imeIPrezime;
    @XmlElement(name = "naziv_zalioca")
    protected String nazivZalioca;
    @XmlElement(name = "adresa_zalioca", required = true)
    protected String adresaZalioca;

    /**
     * Gets the value of the imeIPrezime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeIPrezime() {
        return imeIPrezime;
    }

    /**
     * Sets the value of the imeIPrezime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeIPrezime(String value) {
        this.imeIPrezime = value;
    }

    /**
     * Gets the value of the nazivZalioca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivZalioca() {
        return nazivZalioca;
    }

    /**
     * Sets the value of the nazivZalioca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivZalioca(String value) {
        this.nazivZalioca = value;
    }

    /**
     * Gets the value of the adresaZalioca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresaZalioca() {
        return adresaZalioca;
    }

    /**
     * Sets the value of the adresaZalioca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresaZalioca(String value) {
        this.adresaZalioca = value;
    }

}
