package com.xml.portal.organvlasti.service.soap.zalba_odbijanje;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.xml.portal.organvlasti.data.dao.zalba_odbijanje.ObjectFactory;
import com.xml.portal.organvlasti.data.dao.zalba_odbijanje.ZalbaOdbijanje;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-06T14:17:55.759+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://zalbaodbijanje", name = "ZalbaOdbijenServicePortType")
@XmlSeeAlso({com.xml.portal.organvlasti.data.dao.tipovi.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ZalbaOdbijenServicePortType {

    @WebMethod(action = "http://zalbaodbijanje/ws/sendZalbaOdbijen")
    public void sendZalbaOdbijen(
        @WebParam(partName = "ZalbaOdbijanje", name = "ZalbaOdbijanje")
        ZalbaOdbijanje zalbaOdbijanje
    );
}
