//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.26 at 01:13:39 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://korisnik", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.xml.portal.poverenik.data.dao.korisnik;
