package com.xml.portal.poverenik.service.soap.izvestaj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-04T10:29:01.912+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://izvestaj-service", name = "IzvestajServicePortType")
@XmlSeeAlso({com.xml.portal.poverenik.data.dao.izvestaj.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IzvestajServicePortType {

    @WebMethod(action = "http://izvestaj/ws/sendIzvestaj")
    public void sendIzvestaj(
        @WebParam(partName = "Izvestaj", name = "Izvestaj")
        com.xml.portal.poverenik.data.dao.izvestaj.Izvestaj izvestaj
    );
}
