//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.04 at 07:56:03 PM CET 
//


package zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Dostava_postom" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Dostava_elektronskom_postom" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Dostava_faksom" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="Posebna_dostava">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Nacin_posebne_dostave">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dostavaPostom",
    "dostavaElektronskomPostom",
    "dostavaFaksom",
    "posebnaDostava"
})
@XmlRootElement(name = "Nacin_dostave")
public class NacinDostave {

    @XmlElement(name = "Dostava_postom")
    protected Object dostavaPostom;
    @XmlElement(name = "Dostava_elektronskom_postom")
    protected Object dostavaElektronskomPostom;
    @XmlElement(name = "Dostava_faksom")
    protected Object dostavaFaksom;
    @XmlElement(name = "Posebna_dostava")
    protected NacinDostave.PosebnaDostava posebnaDostava;

    /**
     * Gets the value of the dostavaPostom property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDostavaPostom() {
        return dostavaPostom;
    }

    /**
     * Sets the value of the dostavaPostom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDostavaPostom(Object value) {
        this.dostavaPostom = value;
    }

    /**
     * Gets the value of the dostavaElektronskomPostom property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDostavaElektronskomPostom() {
        return dostavaElektronskomPostom;
    }

    /**
     * Sets the value of the dostavaElektronskomPostom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDostavaElektronskomPostom(Object value) {
        this.dostavaElektronskomPostom = value;
    }

    /**
     * Gets the value of the dostavaFaksom property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDostavaFaksom() {
        return dostavaFaksom;
    }

    /**
     * Sets the value of the dostavaFaksom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDostavaFaksom(Object value) {
        this.dostavaFaksom = value;
    }

    /**
     * Gets the value of the posebnaDostava property.
     * 
     * @return
     *     possible object is
     *     {@link NacinDostave.PosebnaDostava }
     *     
     */
    public NacinDostave.PosebnaDostava getPosebnaDostava() {
        return posebnaDostava;
    }

    /**
     * Sets the value of the posebnaDostava property.
     * 
     * @param value
     *     allowed object is
     *     {@link NacinDostave.PosebnaDostava }
     *     
     */
    public void setPosebnaDostava(NacinDostave.PosebnaDostava value) {
        this.posebnaDostava = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Nacin_posebne_dostave">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nacinPosebneDostave"
    })
    public static class PosebnaDostava {

        @XmlElement(name = "Nacin_posebne_dostave", required = true)
        protected String nacinPosebneDostave;

        /**
         * Gets the value of the nacinPosebneDostave property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNacinPosebneDostave() {
            return nacinPosebneDostave;
        }

        /**
         * Sets the value of the nacinPosebneDostave property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNacinPosebneDostave(String value) {
            this.nacinPosebneDostave = value;
        }

    }

}
