//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.04 at 07:56:03 PM CET 
//


package zahtev;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zahtev package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zahtev
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zahtevi }
     * 
     */
    public Zahtevi createZahtevi() {
        return new Zahtevi();
    }

    /**
     * Create an instance of {@link NacinDostave }
     * 
     */
    public NacinDostave createNacinDostave() {
        return new NacinDostave();
    }

    /**
     * Create an instance of {@link TZakonskaOsnova }
     * 
     */
    public TZakonskaOsnova createTZakonskaOsnova() {
        return new TZakonskaOsnova();
    }

    /**
     * Create an instance of {@link TZakonskaOsnova.SluzbeniGlasnik }
     * 
     */
    public TZakonskaOsnova.SluzbeniGlasnik createTZakonskaOsnovaSluzbeniGlasnik() {
        return new TZakonskaOsnova.SluzbeniGlasnik();
    }

    /**
     * Create an instance of {@link Zahtevi.DostavljanjeKopije }
     * 
     */
    public Zahtevi.DostavljanjeKopije createZahteviDostavljanjeKopije() {
        return new Zahtevi.DostavljanjeKopije();
    }

    /**
     * Create an instance of {@link TeloZahteva }
     * 
     */
    public TeloZahteva createTeloZahteva() {
        return new TeloZahteva();
    }

    /**
     * Create an instance of {@link ZahtevZaPristupInformacijama }
     * 
     */
    public ZahtevZaPristupInformacijama createZahtevZaPristupInformacijama() {
        return new ZahtevZaPristupInformacijama();
    }

    /**
     * Create an instance of {@link TOrganVlasti }
     * 
     */
    public TOrganVlasti createTOrganVlasti() {
        return new TOrganVlasti();
    }

    /**
     * Create an instance of {@link TTrazilac }
     * 
     */
    public TTrazilac createTTrazilac() {
        return new TTrazilac();
    }

    /**
     * Create an instance of {@link NacinDostave.PosebnaDostava }
     * 
     */
    public NacinDostave.PosebnaDostava createNacinDostavePosebnaDostava() {
        return new NacinDostave.PosebnaDostava();
    }

    /**
     * Create an instance of {@link TZakonskaOsnova.SluzbeniGlasnik.Brojevi }
     * 
     */
    public TZakonskaOsnova.SluzbeniGlasnik.Brojevi createTZakonskaOsnovaSluzbeniGlasnikBrojevi() {
        return new TZakonskaOsnova.SluzbeniGlasnik.Brojevi();
    }

}
