//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 09:56:49 PM CET 
//


package zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Zakonska_osnova" type="{http://zahtev}TZakonska_osnova"/>
 *         &lt;element ref="{http://zahtev}Zahtevi"/>
 *         &lt;element name="Zahtevane_informacije" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zakonskaOsnova",
    "zahtevi",
    "zahtevaneInformacije"
})
@XmlRootElement(name = "Telo_zahteva")
public class TeloZahteva {

    @XmlElement(name = "Zakonska_osnova", required = true)
    protected TZakonskaOsnova zakonskaOsnova;
    @XmlElement(name = "Zahtevi", required = true)
    protected Zahtevi zahtevi;
    @XmlElement(name = "Zahtevane_informacije", required = true)
    protected String zahtevaneInformacije;

    /**
     * Gets the value of the zakonskaOsnova property.
     * 
     * @return
     *     possible object is
     *     {@link TZakonskaOsnova }
     *     
     */
    public TZakonskaOsnova getZakonskaOsnova() {
        return zakonskaOsnova;
    }

    /**
     * Sets the value of the zakonskaOsnova property.
     * 
     * @param value
     *     allowed object is
     *     {@link TZakonskaOsnova }
     *     
     */
    public void setZakonskaOsnova(TZakonskaOsnova value) {
        this.zakonskaOsnova = value;
    }

    /**
     * Gets the value of the zahtevi property.
     * 
     * @return
     *     possible object is
     *     {@link Zahtevi }
     *     
     */
    public Zahtevi getZahtevi() {
        return zahtevi;
    }

    /**
     * Sets the value of the zahtevi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zahtevi }
     *     
     */
    public void setZahtevi(Zahtevi value) {
        this.zahtevi = value;
    }

    /**
     * Gets the value of the zahtevaneInformacije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZahtevaneInformacije() {
        return zahtevaneInformacije;
    }

    /**
     * Sets the value of the zahtevaneInformacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZahtevaneInformacije(String value) {
        this.zahtevaneInformacije = value;
    }

}
