//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.30 at 04:56:49 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://korisnik", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.xml.portal.organvlasti.data.dao.korisnik;
