package com.xml.portal.organvlasti.service.soap.zahtev;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T01:43:26.600+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://zahtev", name = "ZahtevServicePortType")
@XmlSeeAlso({com.xml.portal.organvlasti.data.dao.zahtev.ObjectFactory.class, com.xml.portal.organvlasti.data.dao.tipovi.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ZahtevServicePortType {

    @WebMethod(action = "http://zahtev/ws/getZahtev")
    @WebResult(name = "zahtev", targetNamespace = "http://zahtev", partName = "zahtev")
    public com.xml.portal.organvlasti.data.dao.zahtev.Zahtev getZahtev(
        @WebParam(partName = "id", name = "id")
        java.lang.String id
    );
}
