package com.xml.portal.eposta.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.xml.portal.eposta.data.dao.pismo.ObjectFactory;
import com.xml.portal.eposta.data.dao.pismo.Pismo;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T12:04:53.374+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://posta", name = "EpostaServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.DOCUMENT)
public interface EpostaServicePortType {

    @WebMethod(action = "http://eposta/ws/posaljiPoruku")
    public void posaljiPoruku(
        @WebParam(partName = "pismo", name = "pismo")
        Pismo pismo
    );
}
