
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xml.portal.poverenik.service.soap.zalba_odbijanje;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.springframework.stereotype.Service;

import com.xml.portal.poverenik.data.dao.odgovor.Odgovor;
import com.xml.portal.poverenik.data.dao.zalba_odbijanje.ZalbaOdbijanje;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T11:45:01.702+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZalbaOdbijenService",
                      portName = "ZalbaOdbijenServiceSoapBinding",
                      targetNamespace = "http://zalbaodbijanje",
                      wsdlLocation = "src/main/resources/data/wsdl/zalba-odbijanje.wsdl",
                      endpointInterface = "com.xml.portal.poverenik.service.soap.zalba_odbijanje.ZalbaOdbijenServicePortType")
        
@Service  
public class ZalbaOdbijenServiceSoapBindingImpl implements ZalbaOdbijenServicePortType {

    private static final Logger LOG = Logger.getLogger(ZalbaOdbijenServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see zalbaodbijanje.ZalbaOdbijenServicePortType#sendOdgovor(odgovor.Odgovor odgovor)*
     */
    public void sendOdgovor(Odgovor odgovor) { 
        LOG.info("Executing operation sendOdgovor");
        System.out.println(odgovor);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see zalbaodbijanje.ZalbaOdbijenServicePortType#sendZalbaOdbijen(zalbaodbijanje.ZalbaOdbijanje zalbaOdbijanje)*
     */
    public void sendZalbaOdbijen(ZalbaOdbijanje zalbaOdbijanje) { 
        LOG.info("Executing operation sendZalbaOdbijen");
        System.out.println(zalbaOdbijanje);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
