package com.xml.portal.poverenik.service.soap.zalba_odbijanje;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T18:57:13.536+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "ZalbaOdbijenService", 
                  wsdlLocation = "classpath:wsdl/zalba-odbijanje.wsdl",
                  targetNamespace = "http://zalbaodbijanje") 
public class ZalbaOdbijenService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://zalbaodbijanje", "ZalbaOdbijenService");
    public final static QName ZalbaOdbijenServiceSoapBinding = new QName("http://zalbaodbijanje", "ZalbaOdbijenServiceSoapBinding");
    static {
        URL url = ZalbaOdbijenService.class.getClassLoader().getResource("wsdl/zalba-odbijanje.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ZalbaOdbijenService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/zalba-odbijanje.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public ZalbaOdbijenService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZalbaOdbijenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZalbaOdbijenService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZalbaOdbijenService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZalbaOdbijenService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZalbaOdbijenService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ZalbaOdbijenServicePortType
     */
    @WebEndpoint(name = "ZalbaOdbijenServiceSoapBinding")
    public ZalbaOdbijenServicePortType getZalbaOdbijenServiceSoapBinding() {
        return super.getPort(ZalbaOdbijenServiceSoapBinding, ZalbaOdbijenServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZalbaOdbijenServicePortType
     */
    @WebEndpoint(name = "ZalbaOdbijenServiceSoapBinding")
    public ZalbaOdbijenServicePortType getZalbaOdbijenServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(ZalbaOdbijenServiceSoapBinding, ZalbaOdbijenServicePortType.class, features);
    }

}
