package com.xml.portal.poverenik.service.soap.zalba_odbijanje;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.xml.portal.poverenik.data.dao.odgovor.ObjectFactory;
import com.xml.portal.poverenik.data.dao.odgovor.Odgovor;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T18:57:13.532+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://zalbaodbijanje", name = "ZalbaOdbijenServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ZalbaOdbijenServicePortType {

    @WebMethod(action = "http://zalbaodbijanje/ws/receiveOdgovor")
    public void receiveOdgovor(
        @WebParam(partName = "Odgovor", name = "Odgovor")
        Odgovor odgovor
    );
}
