
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xml.portal.poverenik.service.soap.zalba_odbijanje;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.xml.portal.poverenik.business.IzjasnjenjeBusiness;
import com.xml.portal.poverenik.data.dao.odgovor.Odgovor;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T18:57:13.526+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZalbaOdbijenService",
                      portName = "ZalbaOdbijenServiceSoapBinding",
                      targetNamespace = "http://zalbaodbijanje",
                      wsdlLocation = "src/main/resources/data/wsdl/zalba-odbijanje.wsdl",
                      endpointInterface = "com.xml.portal.poverenik.service.soap.zalba_odbijanje.ZalbaOdbijenServicePortType")
@Service       
public class ZalbaOdbijenServiceSoapBindingImpl implements ZalbaOdbijenServicePortType {

    private static final Logger LOG = Logger.getLogger(ZalbaOdbijenServiceSoapBindingImpl.class.getName());

    @Autowired
    private IzjasnjenjeBusiness izjasnjenjeBusiness;
    
    /* (non-Javadoc)
     * @see zalbaodbijanje.ZalbaOdbijenServicePortType#receiveOdgovor(odgovor.Odgovor odgovor)*
     */
    public void receiveOdgovor(Odgovor odgovor) { 
        LOG.info("Executing operation receiveOdgovor");
        System.out.println(odgovor);
        String id = izjasnjenjeBusiness.crete(odgovor);
        System.out.println("Kreirana izjava: " + id);
        try {
        	
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
