//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 11:48:47 PM CET 
//


package com.xml.portal.poverenik.data.dao.izvestaj;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml.portal.poverenik.data.dao.izvestaj package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml.portal.poverenik.data.dao.izvestaj
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Izvestaj }
     * 
     */
    public Izvestaj createIzvestaj() {
    	Izvestaj i = new Izvestaj();
    	i.setZahtevi(new Zahtevi());
        return new Izvestaj();
    }

    /**
     * Create an instance of {@link Zahtevi }
     * 
     */
    public Zahtevi createZahtevi() {
    	Zahtevi z = new Zahtevi();
    	z.setZahteviUkupno(new ZahteviStat());
        return new Zahtevi();
    }

    /**
     * Create an instance of {@link ZahteviStat }
     * 
     */
    public ZahteviStat createZahteviStat() {
    	ZahteviStat zs = new ZahteviStat();
    	zs.setUkupnoNerazresenihZahteva(0);
    	zs.setUkupnoOdbijenihZahtevi(0);
    	zs.setUkupnoPrihvacenihZahteva(0);
    	zs.setUkupnoZahteva(0);
        return new ZahteviStat();
    }

    /**
     * Create an instance of {@link Zalbe }
     * 
     */
    public Zalbe createZalbe() {
        return new Zalbe();
    }

    /**
     * Create an instance of {@link ZalbeStat }
     * 
     */
    public ZalbeStat createZalbeStat() {
        return new ZalbeStat();
    }

}
