//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 11:48:47 PM CET 
//


package com.xml.portal.poverenik.data.dao.izvestaj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="Gradjanin_zahtevi" type="{http://izvestaj}Zahtevi_stat"/&amp;gt;
 *         &amp;lt;element name="Organizacija_ukupno" type="{http://izvestaj}Zahtevi_stat"/&amp;gt;
 *         &amp;lt;element name="Zahtevi_ukupno" type="{http://izvestaj}Zahtevi_stat"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gradjaninZahtevi",
    "organizacijaUkupno",
    "zahteviUkupno"
})
@XmlRootElement(name = "Zahtevi")
public class Zahtevi {

    @XmlElement(name = "Gradjanin_zahtevi", required = true)
    protected ZahteviStat gradjaninZahtevi;
    @XmlElement(name = "Organizacija_ukupno", required = true)
    protected ZahteviStat organizacijaUkupno;
    @XmlElement(name = "Zahtevi_ukupno", required = true)
    protected ZahteviStat zahteviUkupno;

    /**
     * Gets the value of the gradjaninZahtevi property.
     * 
     * @return
     *     possible object is
     *     {@link ZahteviStat }
     *     
     */
    public ZahteviStat getGradjaninZahtevi() {
        return gradjaninZahtevi;
    }

    /**
     * Sets the value of the gradjaninZahtevi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahteviStat }
     *     
     */
    public void setGradjaninZahtevi(ZahteviStat value) {
        this.gradjaninZahtevi = value;
    }

    /**
     * Gets the value of the organizacijaUkupno property.
     * 
     * @return
     *     possible object is
     *     {@link ZahteviStat }
     *     
     */
    public ZahteviStat getOrganizacijaUkupno() {
        return organizacijaUkupno;
    }

    /**
     * Sets the value of the organizacijaUkupno property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahteviStat }
     *     
     */
    public void setOrganizacijaUkupno(ZahteviStat value) {
        this.organizacijaUkupno = value;
    }

    /**
     * Gets the value of the zahteviUkupno property.
     * 
     * @return
     *     possible object is
     *     {@link ZahteviStat }
     *     
     */
    public ZahteviStat getZahteviUkupno() {
        return zahteviUkupno;
    }

    /**
     * Sets the value of the zahteviUkupno property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahteviStat }
     *     
     */
    public void setZahteviUkupno(ZahteviStat value) {
        this.zahteviUkupno = value;
    }

	@Override
	public String toString() {
		return "\n\tZahtevi [\n\t\tgradjaninZahtevi=" + gradjaninZahtevi + ", \n\t\torganizacijaUkupno=" + organizacijaUkupno
				+ ", \n\t\tzahteviUkupno=" + zahteviUkupno + "]";
	}

}
