//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.02 at 11:48:47 PM CET 
//


package com.xml.portal.poverenik.data.dao.izvestaj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="Gradjanin_zalbe" type="{http://izvestaj}Zalbe_stat"/&amp;gt;
 *         &amp;lt;element name="Organizacija_zalbe" type="{http://izvestaj}Zalbe_stat"/&amp;gt;
 *         &amp;lt;element name="Zalbe_ukupno" type="{http://izvestaj}Zalbe_stat"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gradjaninZalbe",
    "organizacijaZalbe",
    "zalbeUkupno"
})
@XmlRootElement(name = "Zalbe")
public class Zalbe {

    @XmlElement(name = "Gradjanin_zalbe", required = true)
    protected ZalbeStat gradjaninZalbe;
    @XmlElement(name = "Organizacija_zalbe", required = true)
    protected ZalbeStat organizacijaZalbe;
    @XmlElement(name = "Zalbe_ukupno", required = true)
    protected ZalbeStat zalbeUkupno;

    /**
     * Gets the value of the gradjaninZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbeStat }
     *     
     */
    public ZalbeStat getGradjaninZalbe() {
        return gradjaninZalbe;
    }

    /**
     * Sets the value of the gradjaninZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbeStat }
     *     
     */
    public void setGradjaninZalbe(ZalbeStat value) {
        this.gradjaninZalbe = value;
    }

    /**
     * Gets the value of the organizacijaZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbeStat }
     *     
     */
    public ZalbeStat getOrganizacijaZalbe() {
        return organizacijaZalbe;
    }

    /**
     * Sets the value of the organizacijaZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbeStat }
     *     
     */
    public void setOrganizacijaZalbe(ZalbeStat value) {
        this.organizacijaZalbe = value;
    }

    /**
     * Gets the value of the zalbeUkupno property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbeStat }
     *     
     */
    public ZalbeStat getZalbeUkupno() {
        return zalbeUkupno;
    }

    /**
     * Sets the value of the zalbeUkupno property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbeStat }
     *     
     */
    public void setZalbeUkupno(ZalbeStat value) {
        this.zalbeUkupno = value;
    }

	@Override
	public String toString() {
		return "\n\tZalbe [\n\t\tgradjaninZalbe=" + gradjaninZalbe + ", \n\t\torganizacijaZalbe=" + organizacijaZalbe + ", \n\t\tzalbeUkupno="
				+ zalbeUkupno + "]";
	}

}
