package com.xml.portal.poverenik.service.soap.zalba_cutanje;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.xml.portal.poverenik.data.dao.odgovor.ObjectFactory;
import com.xml.portal.poverenik.data.dao.odgovor.Odgovor;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T18:38:15.887+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://zalbacutanje", name = "ZalbaCutanjeServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ZalbaCutanjeServicePortType {

    @WebMethod(action = "http://zalbacutanje/ws/receiveOdgovor")
    public void receiveOdgovor(
        @WebParam(partName = "Odgovor", name = "Odgovor")
        Odgovor odgovor
    );
}
