
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xml.portal.poverenik.service.soap.zalba_cutanje;

import java.util.logging.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.xml.portal.poverenik.business.IzjasnjenjeBusiness;
import com.xml.portal.poverenik.business.ZalbaCutanjeBusiness;
import com.xml.portal.poverenik.data.dao.odgovor.Odgovor;
import com.xml.portal.poverenik.data.dao.zalba_cutanje.ZalbaCutanje;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T18:38:15.879+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZalbaCutanjeService",
                      portName = "ZalbaCutanjeServiceSoapBinding",
                      targetNamespace = "http://zalbacutanje",
                      wsdlLocation = "src/main/resources/data/wsdl/zalba-cutanje.wsdl",
                      endpointInterface = "com.xml.portal.poverenik.service.soap.zalba_cutanje.ZalbaCutanjeServicePortType")
@Service
public class ZalbaCutanjeServiceSoapBindingImpl implements ZalbaCutanjeServicePortType {

    private static final Logger LOG = Logger.getLogger(ZalbaCutanjeServiceSoapBindingImpl.class.getName());

    @Autowired
    private IzjasnjenjeBusiness izjasnjenjeBusiness;
    @Autowired
    private ZalbaCutanjeBusiness zalbaCutanjeBusiness;
    
    /* (non-Javadoc)
     * @see zalbacutanje.ZalbaCutanjeServicePortType#receiveOdgovor(odgovor.Odgovor odgovor)*
     */
    public void receiveOdgovor(Odgovor odgovor) { 
        LOG.info("Executing operation receiveOdgovor");
        System.out.println(odgovor);
        String id = izjasnjenjeBusiness.crete(odgovor);
        System.out.println("Kreirana izjava: " + id);
        
        // postavljanje vrednosti izjasnjenje zahteva na true
        ZalbaCutanje zalbaCutanje = zalbaCutanjeBusiness.getById(odgovor.getId());
        zalbaCutanjeBusiness.izjasnjenjeTrue(odgovor.getId(), zalbaCutanje);
        
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
