
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xml.portal.poverenik.service.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.xml.portal.poverenik.business.ZahtevBusiness;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T01:43:26.552+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZahtevService",
                      portName = "ZahtevServiceSoapBinding",
                      targetNamespace = "http://zahtev",
                      wsdlLocation = "src/main/resources/data/wsdl/zahtev.wsdl",
                      endpointInterface = "com.xml.portal.poverenik.service.soap.ZahtevServicePortType")
@Service              
public class ZahtevServiceSoapBindingImpl implements ZahtevServicePortType {

    private static final Logger LOG = Logger.getLogger(ZahtevServiceSoapBindingImpl.class.getName());

    @Autowired
    private ZahtevBusiness zahtevBusiness;
    /* (non-Javadoc)
     * @see zahtev.ZahtevServicePortType#getZahtev(java.lang.String id)*
     */
    public com.xml.portal.poverenik.data.dao.zahtev.Zahtev getZahtev(java.lang.String id) { 
        LOG.info("Executing operation getZahtev");
        System.out.println(id);
        try {
        	return zahtevBusiness.getById(id);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
