//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.10 at 04:29:15 PM CET 
//


package com.xml.portal.poverenik.data.dao.tipovi;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml.portal.poverenik.data.dao.tipovi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml.portal.poverenik.data.dao.tipovi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TOrganVlastiAdresa }
     * 
     */
    public TOrganVlastiAdresa createTOrganVlastiAdresa() {
        return new TOrganVlastiAdresa();
    }

    /**
     * Create an instance of {@link TSluzbeniGlasnik }
     * 
     */
    public TSluzbeniGlasnik createTSluzbeniGlasnik() {
        return new TSluzbeniGlasnik();
    }

    /**
     * Create an instance of {@link TPoverenik }
     * 
     */
    public TPoverenik createTPoverenik() {
        return new TPoverenik();
    }

    /**
     * Create an instance of {@link TLice }
     * 
     */
    public TLice createTLice() {
        return new TLice();
    }

    /**
     * Create an instance of {@link TOrganVlasti }
     * 
     */
    public TOrganVlasti createTOrganVlasti() {
        return new TOrganVlasti();
    }

    /**
     * Create an instance of {@link TLiceKontakt }
     * 
     */
    public TLiceKontakt createTLiceKontakt() {
        return new TLiceKontakt();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TOrganVlastiAdresa.Naziv }
     * 
     */
    public TOrganVlastiAdresa.Naziv createTOrganVlastiAdresaNaziv() {
        return new TOrganVlastiAdresa.Naziv();
    }

    /**
     * Create an instance of {@link TSluzbeniGlasnik.Brojevi }
     * 
     */
    public TSluzbeniGlasnik.Brojevi createTSluzbeniGlasnikBrojevi() {
        return new TSluzbeniGlasnik.Brojevi();
    }

    /**
     * Create an instance of {@link TPoverenik.Naziv }
     * 
     */
    public TPoverenik.Naziv createTPoverenikNaziv() {
        return new TPoverenik.Naziv();
    }

    /**
     * Create an instance of {@link TLice.Ime }
     * 
     */
    public TLice.Ime createTLiceIme() {
        return new TLice.Ime();
    }

    /**
     * Create an instance of {@link TLice.Prezime }
     * 
     */
    public TLice.Prezime createTLicePrezime() {
        return new TLice.Prezime();
    }

    /**
     * Create an instance of {@link TLice.Naziv }
     * 
     */
    public TLice.Naziv createTLiceNaziv() {
        return new TLice.Naziv();
    }

    /**
     * Create an instance of {@link TOrganVlasti.Naziv }
     * 
     */
    public TOrganVlasti.Naziv createTOrganVlastiNaziv() {
        return new TOrganVlasti.Naziv();
    }

}
