//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.08 at 11:32:30 PM CET 
//


package com.xml.portal.organvlasti.data.dao.zalba_odbijanje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TTelo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TTelo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Razlog_zalbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Osnova_zalbe" type="{http://zalbaodbijanje}TZakonska_osnova"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTelo", namespace = "http://zalbaodbijanje", propOrder = {
    "razlogZalbe",
    "osnovaZalbe"
})
public class TTelo {

    @XmlElement(name = "Razlog_zalbe", namespace = "http://zalbaodbijanje", required = true)
    protected String razlogZalbe;
    @XmlElement(name = "Osnova_zalbe", namespace = "http://zalbaodbijanje", required = true)
    protected TZakonskaOsnova osnovaZalbe;

    /**
     * Gets the value of the razlogZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazlogZalbe() {
        return razlogZalbe;
    }

    /**
     * Sets the value of the razlogZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazlogZalbe(String value) {
        this.razlogZalbe = value;
    }

    /**
     * Gets the value of the osnovaZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link TZakonskaOsnova }
     *     
     */
    public TZakonskaOsnova getOsnovaZalbe() {
        return osnovaZalbe;
    }

    /**
     * Sets the value of the osnovaZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link TZakonskaOsnova }
     *     
     */
    public void setOsnovaZalbe(TZakonskaOsnova value) {
        this.osnovaZalbe = value;
    }

}
