//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.05 at 02:06:21 AM CET 
//


package obavestenje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the obavestenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: obavestenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Obavestenje }
     * 
     */
    public Obavestenje createObavestenje() {
        return new Obavestenje();
    }

    /**
     * Create an instance of {@link CeneKopiranja }
     * 
     */
    public CeneKopiranja createCeneKopiranja() {
        return new CeneKopiranja();
    }

    /**
     * Create an instance of {@link TOrganVlasti }
     * 
     */
    public TOrganVlasti createTOrganVlasti() {
        return new TOrganVlasti();
    }

    /**
     * Create an instance of {@link TLice }
     * 
     */
    public TLice createTLice() {
        return new TLice();
    }

    /**
     * Create an instance of {@link UvidUDokument }
     * 
     */
    public UvidUDokument createUvidUDokument() {
        return new UvidUDokument();
    }

    /**
     * Create an instance of {@link TZakon }
     * 
     */
    public TZakon createTZakon() {
        return new TZakon();
    }

    /**
     * Create an instance of {@link TVremeMesto }
     * 
     */
    public TVremeMesto createTVremeMesto() {
        return new TVremeMesto();
    }

    /**
     * Create an instance of {@link Obavestenje.UkupanTrosakKopija }
     * 
     */
    public Obavestenje.UkupanTrosakKopija createObavestenjeUkupanTrosakKopija() {
        return new Obavestenje.UkupanTrosakKopija();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TAdresaUvida }
     * 
     */
    public TAdresaUvida createTAdresaUvida() {
        return new TAdresaUvida();
    }

}
