//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.05 at 02:06:21 AM CET 
//


package obavestenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TAdresa_uvida complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TAdresa_uvida">
 *   &lt;complexContent>
 *     &lt;extension base="{http://obavestenje}TAdresa">
 *       &lt;sequence>
 *         &lt;element name="Kancelarijski_broj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAdresa_uvida", propOrder = {
    "kancelarijskiBroj"
})
public class TAdresaUvida
    extends TAdresa
{

    @XmlElement(name = "Kancelarijski_broj", required = true)
    protected String kancelarijskiBroj;

    /**
     * Gets the value of the kancelarijskiBroj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKancelarijskiBroj() {
        return kancelarijskiBroj;
    }

    /**
     * Sets the value of the kancelarijskiBroj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKancelarijskiBroj(String value) {
        this.kancelarijskiBroj = value;
    }

}
