//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.08 at 11:14:14 PM CET 
//


package com.xml.portal.poverenik.data.dao.zahtev;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml.portal.poverenik.data.dao.zahtev package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml.portal.poverenik.data.dao.zahtev
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zahtevi }
     * 
     */
    public Zahtevi createZahtevi() {
        return new Zahtevi();
    }

    /**
     * Create an instance of {@link NacinDostave }
     * 
     */
    public NacinDostave createNacinDostave() {
        return new NacinDostave();
    }

    /**
     * Create an instance of {@link TZakonskaOsnova }
     * 
     */
    public TZakonskaOsnova createTZakonskaOsnova() {
        return new TZakonskaOsnova();
    }

    /**
     * Create an instance of {@link Zahtevi.DostavljanjeKopije }
     * 
     */
    public Zahtevi.DostavljanjeKopije createZahteviDostavljanjeKopije() {
        return new Zahtevi.DostavljanjeKopije();
    }

    /**
     * Create an instance of {@link TeloZahteva }
     * 
     */
    public TeloZahteva createTeloZahteva() {
        return new TeloZahteva();
    }

    /**
     * Create an instance of {@link Zahtev }
     * 
     */
    public Zahtev createZahtev() {
    	Zahtev zahtev = new Zahtev();
    	zahtev.setVocab("http://www.xml.com/predicate/");
    	zahtev.setRel("pred:vezanGradjanin");
        return zahtev;
    }


    /**
     * Create an instance of {@link NacinDostave.PosebnaDostava }
     * 
     */
    public NacinDostave.PosebnaDostava createNacinDostavePosebnaDostava() {
        return new NacinDostave.PosebnaDostava();
    }

}
