//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.08 at 11:14:14 PM CET 
//


package com.xml.portal.poverenik.data.dao.zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import com.xml.portal.poverenik.data.dao.GenericXML;
import com.xml.portal.poverenik.data.dao.PrintUtil;
import com.xml.portal.poverenik.data.dao.tipovi.TLiceKontakt;
import com.xml.portal.poverenik.data.dao.tipovi.TOrganVlasti;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Organ_vlasti" type="{http://zahtev}TOrgan_vlasti"/>
 *         &lt;element ref="{http://zahtev}Telo_zahteva"/>
 *         &lt;element name="Trazilac" type="{http://zahtev}TTrazilac"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="mesto">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="([A-Z][a-z]+)(\s[A-Z][a-z]+)*"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "organVlasti",
    "teloZahteva",
    "trazilac"
})
@XmlRootElement(name = "Zahtev", namespace = "http://zahtev")
public class Zahtev implements GenericXML {

    @XmlElement(name = "Organ_vlasti", namespace = "http://zahtev", required = true)
    protected TOrganVlasti organVlasti;
    @XmlElement(name = "Telo_zahteva", namespace = "http://zahtev", required = true)
    protected TeloZahteva teloZahteva;
    @XmlElement(name = "Trazilac", namespace = "http://zahtev", required = true)
    protected TLiceKontakt trazilac;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "mesto")
    protected String mesto;
    @XmlAttribute(name = "datum")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlAttribute(name = "razresen")
    protected boolean razresen;
    @XmlAttribute(name = "odbijen")
    protected boolean odbijen;
    @XmlAttribute(name = "vocab")
    protected String vocab;
    @XmlAttribute(name = "about")
    protected String about;
    @XmlAttribute(name = "rel")
    protected String rel;
    @XmlAttribute(name = "href")
    protected String href;

    /**
     * Gets the value of the organVlasti property.
     * 
     * @return
     *     possible object is
     *     {@link TOrganVlasti }
     *     
     */
    public TOrganVlasti getOrganVlasti() {
        return organVlasti;
    }

    /**
     * Sets the value of the organVlasti property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOrganVlasti }
     *     
     */
    public void setOrganVlasti(TOrganVlasti value) {
        this.organVlasti = value;
    }

    /**
     * Gets the value of the teloZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link TeloZahteva }
     *     
     */
    public TeloZahteva getTeloZahteva() {
        return teloZahteva;
    }

    /**
     * Sets the value of the teloZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeloZahteva }
     *     
     */
    public void setTeloZahteva(TeloZahteva value) {
        this.teloZahteva = value;
    }

    /**
     * Gets the value of the trazilac property.
     * 
     * @return
     *     possible object is
     *     {@link TLiceKontakt }
     *     
     */
    public TLiceKontakt getTrazilac() {
        return trazilac;
    }

    /**
     * Sets the value of the trazilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLiceKontakt }
     *     
     */
    public void setTrazilac(TLiceKontakt value) {
        this.trazilac = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the mesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesto() {
        return mesto;
    }

    /**
     * Sets the value of the mesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesto(String value) {
        this.mesto = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }
    
    public boolean getRazresen() {
    	return razresen;
    }
    public void setRazresen(boolean value) {
    	this.razresen = value;
    }
    
    public boolean getOdbijen() {
    	return odbijen;
    }
    public void setOdbijen(boolean value) {
    	this.odbijen = value;
    }
    
    public String getVocab() {
    	return vocab;
    }
    public void setVocab(String value) {
    	this.vocab = value;
    }
    
    public String getAbout() {
    	return about;
    }
    public void setAbout(String value) {
    	this.about = value;
    }

    public String getRel() {
    	return rel;
    }
    public void setRel(String value) {
    	this.rel = value;
    }
    
    public String getHref() {
    	return href;
    }
    public void setHref(String value) {
    	this.href = value;
    }

	@Override
	public String toString() {
		PrintUtil.printZahtev(this);
		return PrintUtil.getOutString();
	}
}
