
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xml.portal.poverenik.service.soap.posta;

import java.net.URL;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.soap.MessageFactory;
import javax.xml.soap.MimeHeaders;
import javax.xml.soap.SOAPBody;
import javax.xml.soap.SOAPConnection;
import javax.xml.soap.SOAPConnectionFactory;
import javax.xml.soap.SOAPEnvelope;
import javax.xml.soap.*;

import org.exist.util.Base64Encoder;
import org.springframework.stereotype.Service;

import com.sun.xml.messaging.saaj.packaging.mime.util.BASE64EncoderStream;
import com.xml.portal.poverenik.data.dao.pismo.Pismo;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T14:02:23.323+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "PoverenikPostaService",
                      portName = "PoverenikPostaServiceSoapBinding",
                      targetNamespace = "http://poverenik-posta",
                      wsdlLocation = "src/main/resources/data/wsdl/poverenik-posta.wsdl",
                      endpointInterface = "com.xml.portal.poverenik.service.soap.posta.PoverenikPostaServicePortType")
@Service              
public class PoverenikPostaServiceSoapBindingImpl implements PoverenikPostaServicePortType {

    private static final Logger LOG = Logger.getLogger(PoverenikPostaServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see poverenik_posta.PoverenikPostaServicePortType#posaljiPoruku()*
     */
    public void posaljiPoruku() { 
        LOG.info("Executing operation posaljiPoruku");
        try {
        	/*PoverenikPostaService service = new PoverenikPostaService(new URL("http://localhost:8080/ws/poverenik-posta?wsdl"));
        	PoverenikPostaServicePortType postaPort = service.getPoverenikPostaServiceSoapBinding();
        	
        	String html = "<!DOCTYPE html>\r\n"
        			+ "<html dir=\"ltr\" lang=\"en\">\r\n"
        			+ "\r\n"
        			+ "<head>\r\n"
        			+ "	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n"
        			+ "	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/alertEmpty.css\">\r\n"
        			+ "    <meta charset=\"utf-8\">\r\n"
        			+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
        			+ "    <!-- Tell the browser to be responsive to screen width -->\r\n"
        			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
        			+ "    <meta name=\"description\" content=\"\">\r\n"
        			+ "    <meta name=\"author\" content=\"\">\r\n"
        			+ "    <!-- Favicon icon -->\r\n"
        			+ "    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"images/favicon.png\">\r\n"
        			+ "    <title>Cloud Service</title>\r\n"
        			+ "    <!-- Custom CSS -->\r\n"
        			+ "    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n"
        			+ "    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n"
        			+ "    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n"
        			+ "    <!--[if lt IE 9]>\r\n"
        			+ "    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n"
        			+ "    <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n"
        			+ "<![endif]-->\r\n"
        			+ "\r\n"
        			+ "	<META Http-Equiv=\"Cache-Control\" Content=\"no-store\">\r\n"
        			+ "	<META Http-Equiv=\"Pragma\" Content=\"no-cache\">\r\n"
        			+ "	<META Http-Equiv=\"Expires\" Content=\"0\">\r\n"
        			+ "	\r\n"
        			+ "	<script type=\"text/javascript\">\r\n"
        			+ "		function preback(){window.history.forward();}\r\n"
        			+ "		setTimeout(\"preback()\", 0)\r\n"
        			+ "		window.onunload=function(){null};\r\n"
        			+ "	</script>\r\n"
        			+ "</head>\r\n"
        			+ "\r\n"
        			+ "<body>\r\n"
        			+ "    <!-- ============================================================== -->\r\n"
        			+ "    <!-- Preloader - style you can find in spinners.css -->\r\n"
        			+ "    <!-- ============================================================== -->\r\n"
        			+ "    <div class=\"preloader\">\r\n"
        			+ "        <div class=\"lds-ripple\">\r\n"
        			+ "            <div class=\"lds-pos\"></div>\r\n"
        			+ "            <div class=\"lds-pos\"></div>\r\n"
        			+ "        </div>\r\n"
        			+ "    </div>\r\n"
        			+ "    <!-- ============================================================== -->\r\n"
        			+ "    <!-- Main wrapper - style you can find in pages.scss -->\r\n"
        			+ "    <!-- ============================================================== -->\r\n"
        			+ "    <div id=\"main-wrapper\" data-navbarbg=\"skin6\" data-theme=\"light\" data-layout=\"vertical\" data-sidebartype=\"full\"\r\n"
        			+ "        data-boxed-layout=\"full\">\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <!-- Topbar header - style you can find in pages.scss -->\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <header class=\"topbar\" data-navbarbg=\"skin6\">\r\n"
        			+ "            <nav class=\"navbar top-navbar navbar-expand-md navbar-light\">\r\n"
        			+ "                <div class=\"navbar-header\" data-logobg=\"skin5\">\r\n"
        			+ "                    <!-- ============================================================== -->\r\n"
        			+ "                    <!-- Logo -->\r\n"
        			+ "                    <!-- ============================================================== -->\r\n"
        			+ "                    <div class=\"navbar-brand\">\r\n"
        			+ "                        <a href=\"#\" class=\"logo\">\r\n"
        			+ "                            <!-- Logo icon -->\r\n"
        			+ "                            <b class=\"logo-icon\">\r\n"
        			+ "                                <!--You can put here icon as well // <i class=\"wi wi-sunset\"></i> //-->\r\n"
        			+ "                                <!-- Dark Logo icon -->\r\n"
        			+ "                                <img src=\"images/cloud_logo.png\" class=\"myLogo\" /></b>\r\n"
        			+ "                            <!--End Logo icon -->\r\n"
        			+ "                        </a>\r\n"
        			+ "                    </div>\r\n"
        			+ "                    <!-- ============================================================== -->\r\n"
        			+ "                    <!-- End Logo -->\r\n"
        			+ "                    <!-- ============================================================== -->\r\n"
        			+ "                    <!-- ============================================================== -->\r\n"
        			+ "                </div>\r\n"
        			+ "                <!-- ============================================================== -->\r\n"
        			+ "                <!-- End Logo -->\r\n"
        			+ "                <!-- ============================================================== -->\r\n"
        			+ "                <div>\r\n"
        			+ "                    <!-- ============================================================== -->\r\n"
        			+ "                    <!-- toggle and nav items -->\r\n"
        			+ "                    <!-- ============================================================== -->\r\n"
        			+ "                    <ul>\r\n"
        			+ "                        <!-- ============================================================== -->\r\n"
        			+ "                        <!-- Search -->\r\n"
        			+ "                        <!-- ============================================================== -->\r\n"
        			+ "                        <h1>Cloud Service</h1>\r\n"
        			+ "                    </ul>\r\n"
        			+ "                    <!-- ============================================================== -->\r\n"
        			+ "                    <!-- Right side toggle and nav items -->\r\n"
        			+ "                    <!-- ============================================================== -->\r\n"
        			+ "                </div>\r\n"
        			+ "            </nav>\r\n"
        			+ "        </header>\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <!-- End Topbar header -->\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <!-- Left Sidebar - style you can find in sidebar.scss  -->\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <aside class=\"left-sidebar\" data-sidebarbg=\"skin5\">\r\n"
        			+ "            <!-- Sidebar scroll-->\r\n"
        			+ "            <div class=\"scroll-sidebar\">\r\n"
        			+ "                <!-- Sidebar navigation-->\r\n"
        			+ "                <nav class=\"sidebar-nav\">\r\n"
        			+ "                    <ul id=\"sidebarnav\">\r\n"
        			+ "                        <li class=\"sidebar-item\">\r\n"
        			+ "                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"#viewProfile\" aria-expanded=\"false\">\r\n"
        			+ "                                <i class=\"mdi mdi-account-network\"></i>\r\n"
        			+ "                                <span class=\"hide-menu\">Profile</span>\r\n"
        			+ "                            </a>\r\n"
        			+ "                        </li>\r\n"
        			+ "                        <li class=\"sidebar-item\">\r\n"
        			+ "                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"#viewVMs\" aria-expanded=\"false\">\r\n"
        			+ "                                <i class=\"mdi mdi-cloud-outline\"></i>\r\n"
        			+ "                                <span class=\"hide-menu\">Virtual Machines</span>\r\n"
        			+ "                            </a>\r\n"
        			+ "                        </li>\r\n"
        			+ "                        <li class=\"sidebar-item\">\r\n"
        			+ "                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"#viewUsers\" aria-expanded=\"false\">\r\n"
        			+ "                                <i class=\"mdi mdi-face\"></i>\r\n"
        			+ "                                <span class=\"hide-menu\">Users</span>\r\n"
        			+ "                            </a>\r\n"
        			+ "                        </li>\r\n"
        			+ "                        <li class=\"sidebar-item\">\r\n"
        			+ "                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"#viewOrganisations\" aria-expanded=\"false\">\r\n"
        			+ "                                <i class=\"mdi mdi-factory\"></i>\r\n"
        			+ "                                <span class=\"hide-menu\">Organisations</span>\r\n"
        			+ "                            </a>\r\n"
        			+ "                        </li>\r\n"
        			+ "                        <li class=\"sidebar-item\">\r\n"
        			+ "                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"#viewDiscs\" aria-expanded=\"false\">\r\n"
        			+ "                                <i class=\"mdi mdi-disk\"></i>\r\n"
        			+ "                                <span class=\"hide-menu\">Discs</span>\r\n"
        			+ "                            </a>\r\n"
        			+ "                        </li>\r\n"
        			+ "                        <li class=\"sidebar-item\">\r\n"
        			+ "                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"#viewCategories\" aria-expanded=\"false\">\r\n"
        			+ "                                <i class=\"mdi mdi-buffer\"></i>\r\n"
        			+ "                                <span class=\"hide-menu\">Categories</span>\r\n"
        			+ "                            </a>\r\n"
        			+ "                        </li>\r\n"
        			+ "                    </ul>\r\n"
        			+ "                </nav>\r\n"
        			+ "                <!-- End Sidebar navigation -->\r\n"
        			+ "            </div>\r\n"
        			+ "            <!-- End Sidebar scroll-->\r\n"
        			+ "        </aside>\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <!-- End Left Sidebar - style you can find in sidebar.scss  -->\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <!-- Page wrapper  -->\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <div class=\"page-wrapper\">\r\n"
        			+ "            <!-- ============================================================== -->\r\n"
        			+ "            <!-- Bread crumb and right sidebar toggle -->\r\n"
        			+ "            <!-- ============================================================== -->\r\n"
        			+ "            <div class=\"page-breadcrumb\">\r\n"
        			+ "                <div class=\"row\">\r\n"
        			+ "                    <div class=\"col-5 align-self-center\">\r\n"
        			+ "                        <h4 class=\"page-title\">Virtual Machines</h4>\r\n"
        			+ "                    </div>\r\n"
        			+ "                    <div class=\"col-7 align-self-center\">\r\n"
        			+ "                        <div class=\"d-flex align-items-center justify-content-end\">\r\n"
        			+ "                            <nav aria-label=\"breadcrumb\">\r\n"
        			+ "                                <ol class=\"breadcrumb\">\r\n"
        			+ "                                    <li class=\"breadcrumb-item\">\r\n"
        			+ "                                        <a id=\"logOut\" href=\"\">Logout</a>\r\n"
        			+ "                                    </li>\r\n"
        			+ "                                </ol>\r\n"
        			+ "                            </nav>\r\n"
        			+ "                        </div>\r\n"
        			+ "                    </div>\r\n"
        			+ "                </div>\r\n"
        			+ "            </div>\r\n"
        			+ "            <!-- ============================================================== -->\r\n"
        			+ "            <!-- End Bread crumb and right sidebar toggle -->\r\n"
        			+ "            <!-- ============================================================== -->\r\n"
        			+ "            <!-- ============================================================== -->\r\n"
        			+ "            <!-- Container fluid  -->\r\n"
        			+ "            <!-- ============================================================== -->\r\n"
        			+ "            <div class=\"container-fluid\">\r\n"
        			+ "                <!-- ============================================================== -->\r\n"
        			+ "                <!-- Start Page Content -->\r\n"
        			+ "                <!-- ============================================================== -->\r\n"
        			+ "                <div class=\"row\">\r\n"
        			+ "                    <div class=\"col-12\">\r\n"
        			+ "                        <div class=\"card\">\r\n"
        			+ "                            <div class=\"card-body\">\r\n"
        			+ "                                <div class=\"table-responsive\" id=\"changeable\">\r\n"
        			+ "                                    <table id=\"fillTable\" class=\"table table-striped\">\r\n"
        			+ "                                        <thead id=\"fillHeader\" class=\"thead-dark\">\r\n"
        			+ "                                            <!-- Dinamicly filled -->\r\n"
        			+ "                                        </thead>\r\n"
        			+ "                                        <tbody id=\"fillBody\">\r\n"
        			+ "                                            <!-- Dinamicly filled -->\r\n"
        			+ "                                        </tbody>\r\n"
        			+ "                                    </table>\r\n"
        			+ "                                </div>\r\n"
        			+ "                            </div>\r\n"
        			+ "                        </div>\r\n"
        			+ "                        <!-- New card with form -->\r\n"
        			+ "                        <div class=\"card\">\r\n"
        			+ "                            <div class=\"card-body\">\r\n"
        			+ "                                <div class=\"table-responsive\">\r\n"
        			+ "                                    <form id =\"fillEditForm\" class=\"form-horizontal m-t-30\">\r\n"
        			+ "                                    	\r\n"
        			+ "                                    </form>\r\n"
        			+ "                                </div>\r\n"
        			+ "                            </div>\r\n"
        			+ "                        </div>\r\n"
        			+ "                    </div>\r\n"
        			+ "                </div>\r\n"
        			+ "            </div>\r\n"
        			+ "            <!-- ============================================================== -->\r\n"
        			+ "            <!-- End PAge Content -->\r\n"
        			+ "            <!-- ============================================================== -->\r\n"
        			+ "            <!-- ============================================================== -->\r\n"
        			+ "            <!-- Right sidebar -->\r\n"
        			+ "            <!-- ============================================================== -->\r\n"
        			+ "            <!-- .right-sidebar -->\r\n"
        			+ "            <!-- ============================================================== -->\r\n"
        			+ "            <!-- End Right sidebar -->\r\n"
        			+ "            <!-- ============================================================== -->\r\n"
        			+ "        </div>\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <!-- End Container fluid  -->\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <!-- footer -->\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <footer class=\"footer text-center\">\r\n"
        			+ "            @Cloud Service Designed and Developt  by Igor Lukic and Ksenija Prcic\r\n"
        			+ "        </footer>\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "        <!-- End footer -->\r\n"
        			+ "        <!-- ============================================================== -->\r\n"
        			+ "    </div>\r\n"
        			+ "    <!-- ============================================================== -->\r\n"
        			+ "    <!-- End Page wrapper  -->\r\n"
        			+ "    <!-- ============================================================== -->\r\n"
        			+ "    </div>\r\n"
        			+ "    <!-- ============================================================== -->\r\n"
        			+ "    <!-- End Wrapper -->\r\n"
        			+ "    <!-- ============================================================== -->\r\n"
        			+ "    <!-- ============================================================== -->\r\n"
        			+ "    <!-- All Jquery -->\r\n"
        			+ "    <!-- ============================================================== -->\r\n"
        			+ "    <script src=\"js/jquery.min.js\"></script>\r\n"
        			+ "   	<script src=\"js/main.js\"></script>\r\n"
        			+ "   	<script src=\"js/users.js\"></script>\r\n"
        			+ "   	<script src=\"js/organisations.js\"></script>\r\n"
        			+ "   	<script src=\"js/categories.js\"></script>\r\n"
        			+ "   	<script src=\"js/discs.js\"></script>\r\n"
        			+ "   	<script src=\"js/vms.js\"></script>\r\n"
        			+ "   	<script src=\"js/profile.js\"></script>\r\n"
        			+ "    <!-- Bootstrap tether Core JavaScript -->\r\n"
        			+ "    <script src=\"js/popper.min.js\"></script>\r\n"
        			+ "    <script src=\"js/bootstrap.min.js\"></script>\r\n"
        			+ "    <!-- slimscrollbar scrollbar JavaScript -->\r\n"
        			+ "    <script src=\"js/sparkline.js\"></script>\r\n"
        			+ "    <!--Wave Effects -->\r\n"
        			+ "    <script src=\"js/waves.js\"></script>\r\n"
        			+ "    <!--Menu sidebar -->\r\n"
        			+ "    <script src=\"js/sidebarmenu.js\"></script>\r\n"
        			+ "    <!--Custom JavaScript -->\r\n"
        			+ "    <script src=\"js/custom.min.js\"></script>\r\n"
        			+ "</body>\r\n"
        			+ "\r\n"
        			+ "</html>";
        	
        	Pismo pismo = new Pismo();
        	pismo.setTipPriloga("html");
        	pismo.setNaslov("Poslato iz poverenika");
        	pismo.setPrimalac("igi.l.1999@gmail.com");
        	pismo.setSadrzaj("Sadrzzaj poruke");
        	pismo.setPrilog(BASE64EncoderStream.encode(html.getBytes()));
        	
        	postaPort.posaljiPoruku();*/
        	String soapEndpointUrl = "https://www.w3schools.com/xml/tempconvert.asmx";
            String soapAction = "https://www.w3schools.com/xml/CelsiusToFahrenheit";
            
            SOAPConnectionFactory soapConnectionFactory = SOAPConnectionFactory.newInstance();
            SOAPConnection soapConnection = soapConnectionFactory.createConnection();

            
            MessageFactory messageFactory = MessageFactory.newInstance();
            SOAPMessage soapMessage = messageFactory.createMessage();
            
            SOAPPart soapPart = soapMessage.getSOAPPart();

            String myNamespace = "myNamespace";
            String myNamespaceURI = "https://www.w3schools.com/xml/";

            // SOAP Envelope
            SOAPEnvelope envelope = soapPart.getEnvelope();
            envelope.addNamespaceDeclaration(myNamespace, myNamespaceURI);

            SOAPBody soapBody = envelope.getBody();
            SOAPElement soapBodyElem = soapBody.addChildElement("CelsiusToFahrenheit", myNamespace);
            SOAPElement soapBodyElem1 = soapBodyElem.addChildElement("Celsius", myNamespace);
            soapBodyElem1.addTextNode("100");

            MimeHeaders headers = soapMessage.getMimeHeaders();
            headers.addHeader("SOAPAction", soapAction);

            soapMessage.saveChanges();

            /* Print the request message, just for debugging purposes */
            System.out.println("Request SOAP Message:");
            soapMessage.writeTo(System.out);
            System.out.println("\n");
            // Send SOAP Message to SOAP Server
            SOAPMessage soapResponse = soapConnection.call(soapMessage, soapEndpointUrl);

            // Print the SOAP Response
            System.out.println("Response SOAP Message:");
            soapResponse.writeTo(System.out);
            System.out.println();

            soapConnection.close();
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
