package com.xml.portal.poverenik.service.soap.posta;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T14:02:23.332+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://poverenik-posta", name = "PoverenikPostaServicePortType")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PoverenikPostaServicePortType {

    @WebMethod(action = "http://ws/posaljiPoruku")
    public void posaljiPoruku();
}
